image: java:8-jdk
stages:
  - build
  - test
  - package

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export ANDROID_HOME="/opt/android-sdk"
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build_webserver:
  stage: build
  script:
    - ls
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && chmod +x ./gradlew
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew assemble
test_webserver:
  stage: test
  script:
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && chmod +x ./gradlew
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew check
    
package_webserver:
  stage: package
  script:
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && chmod +x ./gradlew
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew build
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew jar
    - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew build
  artifacts:
    paths:
    - /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver/build/libs/*.jar
    - /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/webserver/build/libs/*.jar.original
build_app:
  stage: build
  script:
  - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A && chmod +x ./gradlew
  - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A && ./gradlew assemble
test_app:
  stage: test
  script:
  - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A && chmod +x ./gradlew
  - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A && ./gradlew check
package_app:
  stage: package
  script:
  - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A && chmod +x ./gradlew
  - cd /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A && ./gradlew assemble
  artifacts:
    paths:
    - /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A/app/build/outputs/apk/*.apk
    - /home/gitlab-runner/builds/28d81fbf/0/BartlomiejRasztabiga/Klasa1AApp/app/Klasa1A/app/build/outputs/mapping/release/mapping.txt
after_script:
  - echo "End CI"