image: java:8-jdk
stages:
  - build_webserver
  - test_webserver
  - package_webserver
before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build_webserver:
  stage: build_webserver
  script:
    - ls
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && chmod +x ./gradlew
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew assemble
  only:
    - master
test_webserver:
  stage: test_webserver
  script:
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && chmod +x ./gradlew
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew check
    
package_webserver:
  stage: package_webserver
  script:
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && chmod +x ./gradlew
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlwe build
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew jar
    - cd /builds/BartlomiejRasztabiga/Klasa1AApp/webserver && ./gradlew build
  artifacts:
    paths:
    - build/libs/*.jar
    - build/libs/*.jar.original
after_script:
  - echo "End CI"